# 小写字母的数量
lowercase: 2
# 大写字母的数量
uppercase: 3
# 数字的数量
numbers: 1
# 符号的数量
symbols: 1
# 密码的总长度
total_length: 10
# 是否随机长度
random_length: true
# 数字的最小长度
number: 5
# 自定义字符集
custom_set: null
# 自定义模式
pattern: null
# 排除的字符
exclude_chars: "0O"
# 输出格式
output_format: text
